openapi: 3.0.3
info:
  title: Mekan ve Yorum Yönetim API'si
  version: 1.0.0
  description: >
    Bu API, mekanların ve bu mekanlara ait kullanıcı yorumlarının yönetilmesi için
    tasarlanmış bir RESTful servistir. Temel CRUD (Create, Read, Update, Delete) işlemlerini
    destekler. Mekanlar coğrafi koordinatlara göre sorgulanabilir ve her mekana kullanıcılar
    tarafından yorum bırakılabilir. API, JWT tabanlı kimlik doğrulama ile korunmaktadır.
  contact:
    name: Asım Sinan Yüksel
    email: asimyuksel@sdu.edu.tr

servers:
  - url: https://api.vercel.com
    description: Üretim sunucusu (Production)
  - url: https://staging-api.vercel.com
    description: Test sunucusu (Staging)
  - url: https://localhost:3000
    description: Yerel geliştirme sunucusu (Development)

tags:
  - name: Mekanlar
    description: Mekan oluşturma, listeleme, güncelleme ve silme işlemleri
  - name: Yorumlar
    description: Mekanlara ait yorum oluşturma, görüntüleme, güncelleme ve silme işlemleri

security:
  - BearerAuth: []

paths:
  /api/venues:
    post:
      tags:
        - Mekanlar
      summary: Mekan Ekle
      operationId: addVenue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VenueInput'
      responses:
        "201":
          description: Mekan başarıyla oluşturuldu
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Venue'
        "400":
          description: Geçersiz istek verisi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Kimlik doğrulama başarısız (token eksik veya geçersiz)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Bu işlem için yetkiniz bulunmuyor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
        - Mekanlar
      summary: Yakındaki Mekanları Listele
      operationId: listNearbyVenues
      parameters:
        - name: lat
          in: query
          required: true
          description: Enlem değeri (latitude)
          schema:
            type: number
            format: float
          example: 37.7749
        - name: long
          in: query
          required: true
          description: Boylam değeri (longitude)
          schema:
            type: number
            format: float
          example: 35.3213
        - name: page
          in: query
          required: false
          description: Sayfa numarası (varsayılan 1)
          schema:
            type: integer
            minimum: 1
            default: 1
          example: 1
        - name: limit
          in: query
          required: false
          description: Sayfa başına sonuç sayısı (varsayılan 10, maksimum 50)
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
          example: 10
      responses:
        "200":
          description: Yakındaki mekanlar başarıyla listelendi
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Venue'
        "400":
          description: Geçersiz koordinatlar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Kimlik doğrulama başarısız (token eksik veya geçersiz)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/venues/{venueid}:
    parameters:
      - name: venueid
        in: path
        required: true
        description: Mekanın benzersiz kimlik numarası
        schema:
          type: string
        example: "abc123"

    get:
      tags:
        - Mekanlar
      summary: Mekan Getir
      operationId: getVenue
      responses:
        "200":
          description: Mekan başarıyla getirildi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Venue'
        "401":
          description: Kimlik doğrulama başarısız (token eksik veya geçersiz)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Mekan bulunamadı
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags:
        - Mekanlar
      summary: Mekan Güncelle
      operationId: updateVenue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VenueInput'
      responses:
        "200":
          description: Mekan başarıyla güncellendi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Venue'
        "400":
          description: Geçersiz istek verisi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Kimlik doğrulama başarısız (token eksik veya geçersiz)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Bu işlem için yetkiniz bulunmuyor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Mekan bulunamadı
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - Mekanlar
      summary: Mekan Sil
      operationId: deleteVenue
      responses:
        "204":
          description: Mekan başarıyla silindi
        "401":
          description: Kimlik doğrulama başarısız (token eksik veya geçersiz)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Bu işlem için yetkiniz bulunmuyor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Mekan bulunamadı
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/venues/{venueid}/comments:
    parameters:
      - name: venueid
        in: path
        required: true
        description: Yorumun ait olduğu mekanın kimlik numarası
        schema:
          type: string
        example: "abc123"

    get:
      tags:
        - Yorumlar
      summary: Yorumları Listele
      operationId: listComments
      parameters:
        - name: page
          in: query
          required: false
          description: Sayfa numarası (varsayılan 1)
          schema:
            type: integer
            minimum: 1
            default: 1
          example: 1
        - name: limit
          in: query
          required: false
          description: Sayfa başına sonuç sayısı (varsayılan 10, maksimum 50)
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
          example: 10
      responses:
        "200":
          description: Yorumlar başarıyla listelendi
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        "401":
          description: Kimlik doğrulama başarısız (token eksik veya geçersiz)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Mekan bulunamadı
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - Yorumlar
      summary: Yorum Ekle
      operationId: addComment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentInput'
      responses:
        "201":
          description: Yorum başarıyla oluşturuldu
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        "400":
          description: Geçersiz istek verisi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Kimlik doğrulama başarısız (token eksik veya geçersiz)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Mekan bulunamadı
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/venues/{venueid}/comments/{commentid}:
    parameters:
      - name: venueid
        in: path
        required: true
        description: Yorumun ait olduğu mekanın kimlik numarası
        schema:
          type: string
        example: "abc123"
      - name: commentid
        in: path
        required: true
        description: Yorumun benzersiz kimlik numarası
        schema:
          type: string
        example: "cmt456"

    get:
      tags:
        - Yorumlar
      summary: Yorum Getir
      operationId: getComment
      responses:
        "200":
          description: Yorum başarıyla getirildi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        "401":
          description: Kimlik doğrulama başarısız (token eksik veya geçersiz)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Yorum bulunamadı
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags:
        - Yorumlar
      summary: Yorum Güncelle
      operationId: updateComment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentInput'
      responses:
        "200":
          description: Yorum başarıyla güncellendi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        "400":
          description: Geçersiz istek verisi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Kimlik doğrulama başarısız (token eksik veya geçersiz)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Bu işlem için yetkiniz bulunmuyor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Yorum bulunamadı
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - Yorumlar
      summary: Yorum Sil
      operationId: deleteComment
      responses:
        "204":
          description: Yorum başarıyla silindi
        "401":
          description: Kimlik doğrulama başarısız (token eksik veya geçersiz)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Bu işlem için yetkiniz bulunmuyor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Yorum bulunamadı
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    BearerAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'JWT tabanlı kimlik doğrulama. İstek başlığına "Authorization: Bearer <token>" eklenmeli.'

  schemas:
    Venue:
      type: object
      description: Mekan bilgilerini temsil eden model
      properties:
        _id:
          type: string
          description: Mekanın benzersiz kimlik numarası (otomatik atanır)
          example: "abc123"
        name:
          type: string
          description: Mekan adı
          example: "Kafe Mavi"
        address:
          type: string
          description: Mekanın açık adresi
          example: "Atatürk Cad. No:12, Ankara"
        rating:
          type: integer
          description: Mekan puanı (1-5 arası)
          minimum: 1
          maximum: 5
          example: 4
        facilities:
          type: array
          description: Mekanda sunulan olanaklar
          items:
            type: string
          example: ["Wi-Fi", "Otopark", "Canlı Müzik"]
        coords:
          type: object
          description: Mekanın coğrafi koordinatları
          properties:
            lat:
              type: number
              format: float
              description: Enlem değeri
              example: 37.7749
            long:
              type: number
              format: float
              description: Boylam değeri
              example: 35.3213
          required:
            - lat
            - long
      required:
        - name
        - address
        - coords

    VenueInput:
      type: object
      description: Mekan oluşturma veya güncelleme isteği için gönderilecek veri
      properties:
        name:
          type: string
          description: Mekan adı
          minLength: 2
          maxLength: 100
          example: "Kafe Mavi"
        address:
          type: string
          description: Mekanın açık adresi
          minLength: 5
          example: "Atatürk Cad. No:12, Ankara"
        rating:
          type: integer
          description: Mekan puanı (1-5 arası)
          minimum: 1
          maximum: 5
          example: 4
        facilities:
          type: array
          description: Mekanda sunulan olanaklar
          items:
            type: string
          example: ["Wi-Fi", "Otopark"]
        coords:
          type: object
          description: Mekanın coğrafi koordinatları
          properties:
            lat:
              type: number
              format: float
              description: Enlem değeri
              example: 37.7749
            long:
              type: number
              format: float
              description: Boylam değeri
              example: 35.3213
          required:
            - lat
            - long
      required:
        - name
        - address
        - coords

    Comment:
      type: object
      description: Yorum bilgilerini temsil eden model
      properties:
        _id:
          type: string
          description: Yorumun benzersiz kimlik numarası (otomatik atanır)
          example: "cmt456"
        author:
          type: string
          description: Yorumu yazan kullanıcının adı
          example: "Ahmet Yılmaz"
        rating:
          type: integer
          description: Kullanıcının verdiği puan (1-5 arası)
          minimum: 1
          maximum: 5
          example: 5
        text:
          type: string
          description: Yorum metni
          example: "Harika bir mekan, kesinlikle tavsiye ederim!"
        createdOn:
          type: string
          format: date-time
          description: Yorumun oluşturulma tarihi (ISO 8601 formatında)
          example: "2026-02-20T14:30:00Z"
      required:
        - author
        - rating
        - text

    CommentInput:
      type: object
      description: Yorum oluşturma veya güncelleme isteği için gönderilecek veri
      properties:
        author:
          type: string
          description: Yorumu yazan kullanıcının adı
          minLength: 2
          maxLength: 50
          example: "Ahmet Yılmaz"
        rating:
          type: integer
          description: Kullanıcının verdiği puan (1-5 arası)
          minimum: 1
          maximum: 5
          example: 5
        text:
          type: string
          description: Yorum metni
          minLength: 5
          maxLength: 500
          example: "Harika bir mekan, kesinlikle tavsiye ederim!"
      required:
        - author
        - rating
        - text

    Error:
      type: object
      description: Hata durumlarında döndürülen standart hata yanıtı
      properties:
        message:
          type: string
          description: Hatayı açıklayan mesaj
          example: "Mekan bulunamadı"
      required:
        - message
