// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TespitSozluk.API.Data;

#nullable disable

namespace TespitSozluk.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317120000_AddEntryVoteEntity")]
    partial class AddEntryVoteEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");
#pragma warning restore 612, 618
        }
    }
}
